controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

cv_download:
    path: /download-cv
    controller: App\Controller\AccueilController::downloadCv